-- Create a blank table
CREATE OR REPLACE TABLE POLICY_EVENTS (
    POLICY_ID INT,
    POLICY_NAME STRING,
    POLICY_CATEGORY STRING,
    START_DATE DATE,
    END_DATE DATE,
    POLICY_LEVEL STRING,
    SOURCE_URL STRING
);